# Generated by Django 6.0.5 on 2026-05-09 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hrbp', models.ForeignKey(limit_choices_to={'role': 'HRBP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=50)),
                ('corporate_id', models.CharField(max_length=50, unique=True)),
                ('matricule', models.CharField(max_length=50)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.poste')),
            ],
        ),
        migrations.CreateModel(
            name='RepriseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence_debut', models.DateField()),
                ('date_absence_fin', models.DateField()),
                ('type_absence', models.CharField(choices=[('MALADIE', 'Maladie'), ('INJUSTIFIEE', 'Absence injustifiée')], max_length=50)),
                ('reason', models.TextField()),
                ('is_repetitive', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, choices=[('2eme absence', '2eme absence'), ('3eme absence', '3eme absence'), ('4eme absence', '4eme absence'), ('plus de 4 fois', 'plus de 4 fois')], max_length=30, null=True)),
                ('cons_reorganization', models.BooleanField(default=False, verbose_name="Réorganisation de l'équipe")),
                ('cons_recruitment', models.BooleanField(default=False, verbose_name='Recrutement')),
                ('cons_departure', models.BooleanField(default=False, verbose_name='Départ de collaborateurs')),
                ('cons_other', models.BooleanField(default=False, verbose_name='Autres (à préciser)')),
                ('cons_other_details', models.TextField(blank=True, null=True)),
                ('action_adjustment', models.BooleanField(default=False, verbose_name='Aménagement du temps de travail')),
                ('action_training', models.BooleanField(default=False, verbose_name='Formation et tutorat')),
                ('action_reassignment', models.BooleanField(default=False, verbose_name='Réaffectation à un autre poste')),
                ('action_deskilling', models.BooleanField(default=False, verbose_name='Déshabilitation ses nouvelles opérations')),
                ('new_missions', models.TextField(blank=True, null=True)),
                ('medical_visit_required', models.BooleanField(default=False, verbose_name='Envoit pour une visite médicale de reprise')),
                ('direct_return', models.BooleanField(default=False, verbose_name='Reprise de poste directement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.collaborateur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.dpt')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'NPLUS1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poste',
            name='uep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.uep'),
        ),
    ]
