# Generated by Django 6.0.5 on 2026-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repriseform',
            name='type_absence',
            field=models.CharField(choices=[('Maladie', 'Maladie'), ('Absence injustifiée', 'Absence injustifiée')], max_length=50),
        ),
    ]
